import { Project, TextLayer } from './types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    name: '智能运动手表_主图_CN.jpg',
    thumbnail: 'https://picsum.photos/id/175/300/300',
    status: 'completed',
    currentStage: 'done',
    sourceLang: '中文(简体)',
    targetLang: '英语',
    domain: '3C数码',
    createTime: '12-02 14:20:00',
    itemCount: 1
  },
  {
    id: '2',
    name: '全自动咖啡机_详情页_01.png',
    thumbnail: 'https://picsum.photos/id/1060/300/300',
    status: 'processing',
    currentStage: 'translating', 
    sourceLang: '中文(简体)',
    targetLang: '德语',
    domain: '家用电器',
    createTime: '12-02 14:15:30',
    itemCount: 1
  },
  {
    id: '3',
    name: '女士瑜伽服_尺码表.jpg',
    thumbnail: 'https://picsum.photos/id/1025/300/300',
    status: 'processing',
    currentStage: 'ocr',
    sourceLang: '中文(简体)',
    targetLang: '日语',
    domain: '服饰鞋包',
    createTime: '12-02 14:10:05',
    itemCount: 1
  },
  {
    id: '4',
    name: '进口面膜_成分说明.jpg',
    thumbnail: 'https://picsum.photos/id/64/300/300',
    status: 'failed',
    currentStage: 'ocr',
    sourceLang: '韩语',
    targetLang: '中文(简体)',
    domain: '美妆护肤',
    createTime: '12-01 09:12:00',
    itemCount: 1
  }
];

export const MOCK_LAYERS: TextLayer[] = [
  {
    id: 'l1',
    originalText: '超长续航',
    translatedText: 'Long Battery Life',
    translationEngine: 'aliyun',
    x: 10,
    y: 10,
    width: 35,
    height: 8,
    fontSize: 24,
    fontFamily: 'Inter',
    color: '#1F2937',
    backgroundColor: 'transparent',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
    alignment: 'left',
    letterSpacing: 0,
    lineHeight: 1.2,
    isVisible: true,
  },
  {
    id: 'l2',
    originalText: '心率监测',
    translatedText: 'Heart Rate Monitor',
    translationEngine: 'aliyun',
    x: 10,
    y: 25,
    width: 40,
    height: 8,
    fontSize: 18,
    fontFamily: 'Inter',
    color: '#4B5563',
    backgroundColor: 'transparent',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    alignment: 'left',
    letterSpacing: 0,
    lineHeight: 1.2,
    isVisible: true,
  },
  {
    id: 'l3',
    originalText: '限时特惠',
    translatedText: 'Limited Offer',
    translationEngine: 'gpt4',
    x: 65,
    y: 10,
    width: 25,
    height: 10,
    fontSize: 20,
    fontFamily: 'Inter',
    color: '#DC2626',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    fontWeight: 'bold',
    fontStyle: 'italic',
    textDecoration: 'none',
    alignment: 'center',
    letterSpacing: 1,
    lineHeight: 1.4,
    isVisible: true,
  }
];

export const COMMON_QUESTIONS = [
  '如何提高复杂背景文字的还原度？',
  '支持导出 PSD 分层文件吗？',
  '图片翻译的计费标准是什么？',
  '如何批量上传文件夹？',
  '支持哪些语种的自动检测？'
];
